services:
  django:
    build: .
    restart: always
    env_file: .env
    networks:
      - local_network
    ports:
      - "127.0.0.1:8000:8000"

    volumes:
      - .:/src/
    depends_on:
      - redis
      - postgres

  bot:
    build: .
    command: "python3 manage.py runbot"
    restart: always
    env_file: .env
    networks:
      - local_network
    volumes:
      - .:/src/
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    restart: always
    networks:
      - local_network
    ports:
      - "127.0.0.1:6379:6379"

  postgres:
    image: postgres:latest
    env_file: .env
    networks:
      - local_network
    ports:
      - "127.0.0.1:5432:5432"

networks:
  local_network:
    driver: bridge
