services:
  django:
    build: .
    restart: always
    env_file: .env
    ports:
      - "127.0.0.1:8000:8000"

    volumes:
      - .:/src/

  bot:
    build: .
    command: "python3 manage.py runbot"
    restart: always
    env_file: .env
    volumes:
      - .:/src/
