services:
  django:
    # build: .
    image: chenar/cstbot:latest
    restart: always
    env_file: .env
    networks:
      - local_network
    ports:
      - 8000:8000

    volumes:
      - .:/src/
    depends_on:
      - redis
      - postgres

  bot:
    # build: .
    image: chenar/cstbot:latest
    command: "python3 manage.py runbot"
    restart: always
    env_file: .env
    networks:
      - local_network
    volumes:
      - .:/src/
    depends_on:
      - redis
      - postgres
      - django

  redis:
    image: redis:latest
    restart: always
    networks:
      - local_network

  postgres:
    image: postgres:latest
    env_file: .env
    networks:
      - local_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  local_network:
    driver: bridge

volumes:
  postgres_data:
