# Generated by Django 5.1.3 on 2024-11-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="text",
            name="title",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="text",
            unique_together={("title", "is_button")},
        ),
    ]
