# Generated by Django 5.1.3 on 2024-11-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_text_title_alter_text_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.IntegerField(choices=[(1, 'general'), (2, 'foundational'), (3, 'specialized'), (4, 'optional')], default=1, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='unit_type',
            field=models.IntegerField(choices=[(1, 'theoretical'), (2, 'practical')], default=1, verbose_name='Unit Type'),
        ),
        migrations.AlterField(
            model_name='place',
            name='group',
            field=models.IntegerField(choices=[(1, 'gate'), (2, 'restaurant'), (3, 'dorm'), (4, 'faculty'), (5, 'bank'), (6, 'office_building'), (7, 'other')], default=7, verbose_name='Place Type'),
        ),
    ]
