"""
Django settings for cstbot project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse

import config

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.SECRET_KEY

if not SECRET_KEY:
    import secrets
    SECRET_KEY = secrets.token_urlsafe(50)
    with open(".env", "a") as env_file:
        env_file.write(f"\nSECRET_KEY=\"{SECRET_KEY}\"")

    import logging
    logger = logging.getLogger(__name__)
    logger.warning("WARNING: SECRET_KEY not set! Generated and saved to .env.")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.DEBUG

CORS_ORIGIN_ALLOW_ALL = DEBUG

ALLOWED_HOSTS = [urlparse(config.BASE_URL).hostname]
CORS_ALLOWED_ORIGINS = [config.BASE_URL]

CSRF_TRUSTED_ORIGINS = [config.BASE_URL]
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

if DEBUG:
    ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cstbot.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cstbot.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config.POSTGRES_DB,
        "USER": config.POSTGRES_USER,
        "PASSWORD": config.POSTGRES_PASSWORD,
        "HOST": config.POSTGRES_HOST,
        "PORT": config.POSTGRES_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


UNFOLD = {
    "SITE_TITLE": "Computer Science Tabriz Bot Panel",
    "SITE_HEADER": "CST Bot Panel",
    "SITE_URL": "/",
    "THEME": "dark",
    "SHOW_HISTORY": True,
    "ENVIRONMENT": "core.unfold.username_badge",
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Management",
                "separator": False,
                "collapsible": False,
                "items": [
                    {
                        "title": "Courses",
                        "icon": "book_3",
                        "badge": "core.unfold.courses_count",
                        "link": reverse_lazy("admin:core_course_changelist"),
                    },
                    {
                        "title": "Places",
                        "icon": "apartment",
                        "badge": "core.unfold.places_count",
                        "link": reverse_lazy("admin:core_place_changelist"),
                    },
                    {
                        "title": "Links",
                        "icon": "link",
                        "badge": "core.unfold.links_count",
                        "link": reverse_lazy("admin:core_link_changelist"),
                    },
                    {
                        "title": "Phones",
                        "icon": "call",
                        "badge": "core.unfold.phones_count",
                        "link": reverse_lazy("admin:core_phone_changelist"),
                    },
                    {
                        "title": "Users",
                        "icon": "people",
                        "badge": "core.unfold.users_count",
                        "link": reverse_lazy("admin:core_tguser_changelist"),
                    },
                    {
                        "title": "Texts",
                        "icon": "edit_note",
                        "badge": "core.unfold.texts_count",
                        "link": reverse_lazy("admin:core_text_changelist"),
                    },
                ],
            },
        ],
    },
}
